/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Integration } from "./Integration";
import { IntegrationCountArgs } from "./IntegrationCountArgs";
import { IntegrationFindManyArgs } from "./IntegrationFindManyArgs";
import { IntegrationFindUniqueArgs } from "./IntegrationFindUniqueArgs";
import { CreateIntegrationArgs } from "./CreateIntegrationArgs";
import { UpdateIntegrationArgs } from "./UpdateIntegrationArgs";
import { DeleteIntegrationArgs } from "./DeleteIntegrationArgs";
import { Project } from "../../project/base/Project";
import { IntegrationService } from "../integration.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Integration)
export class IntegrationResolverBase {
  constructor(
    protected readonly service: IntegrationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Integration",
    action: "read",
    possession: "any",
  })
  async _integrationsMeta(
    @graphql.Args() args: IntegrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Integration])
  @nestAccessControl.UseRoles({
    resource: "Integration",
    action: "read",
    possession: "any",
  })
  async integrations(
    @graphql.Args() args: IntegrationFindManyArgs
  ): Promise<Integration[]> {
    return this.service.integrations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Integration, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Integration",
    action: "read",
    possession: "own",
  })
  async integration(
    @graphql.Args() args: IntegrationFindUniqueArgs
  ): Promise<Integration | null> {
    const result = await this.service.integration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Integration)
  @nestAccessControl.UseRoles({
    resource: "Integration",
    action: "create",
    possession: "any",
  })
  async createIntegration(
    @graphql.Args() args: CreateIntegrationArgs
  ): Promise<Integration> {
    return await this.service.createIntegration({
      ...args,
      data: {
        ...args.data,

        project: args.data.project
          ? {
              connect: args.data.project,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Integration)
  @nestAccessControl.UseRoles({
    resource: "Integration",
    action: "update",
    possession: "any",
  })
  async updateIntegration(
    @graphql.Args() args: UpdateIntegrationArgs
  ): Promise<Integration | null> {
    try {
      return await this.service.updateIntegration({
        ...args,
        data: {
          ...args.data,

          project: args.data.project
            ? {
                connect: args.data.project,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Integration)
  @nestAccessControl.UseRoles({
    resource: "Integration",
    action: "delete",
    possession: "any",
  })
  async deleteIntegration(
    @graphql.Args() args: DeleteIntegrationArgs
  ): Promise<Integration | null> {
    try {
      return await this.service.deleteIntegration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Project, {
    nullable: true,
    name: "project",
  })
  @nestAccessControl.UseRoles({
    resource: "Project",
    action: "read",
    possession: "any",
  })
  async getProject(
    @graphql.Parent() parent: Integration
  ): Promise<Project | null> {
    const result = await this.service.getProject(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
